- name: Create Snapshots of the instance disks
  hosts: localhost
  gather_facts: no

  vars_prompt:
   - name: Instancename
     prompt: "Please enter the instance name for which you wish to create snapshots"
     private: no

  vars:
      gcp_project: hp-ansible-automation-318010
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /etc/ansible/auth.json

  tasks:

   - name: Check date and use it as snapshot suffix
     local_action: command date +"%d-%m-%y"
     register: date

   - name: create a snapshot
     google.cloud.gcp_compute_snapshot:
       name: "{{ Instancename }}"
       source_disk: "{{ Instancename }}"
       service_account_email: ansible@hp-ansible-automation-318010.iam.gserviceaccount.com
       project: "{{ gcp_project }}"
       auth_kind: serviceaccount
       service_account_file: "{{ gcp_cred_file }}"
       state: present


#   - name: Create gce snapshot
#     google.cloud.gcp_compute_snapshot:
#       instance_name: "{{ Instancename }}"
#       snapshot_name: "{{ Instancename }}-{{ date.stdout }}"
#       state: present
#       service_account_email: ansible@hp-ansible-automation-318010.iam.gserviceaccount.com
#       credentials_file: "{{ gcp_cred_file }}"
#       project_id: "{{ gcp_project }}"


