---
- name: Install the zabbix rpm from a remote repo
  yum:
     name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
     state: present

- name: Wait for 30 seconds
  pause:
     seconds: 30

- name: Install zabbix-agent-5.0
  yum:
     name: "zabbix-agent.x86_64"
     state: present

- name: Start and enable zabbix service
  service:
     name: zabbix-agent
     state: started
     enabled: yes

- name: Comment default entries (Hostname and LogFileSize)
  shell: sed -i 's/\(^Hostname=\|^LogFileSize=\)/#\1/' /etc/zabbix/zabbix_agentd.conf

- name: Add zabbix server IP 35.226.192.158 in /etc/zabbix/zabbix_agentd.conf
  shell: sed -i 's/Server=127.0.0.1/Server=35.226.192.158/g' /etc/zabbix/zabbix_agentd.conf; sed -i 's/ServerActive=127.0.0.1/ServerActive=35.226.192.158/g' /etc/zabbix/zabbix_agentd.conf; service zabbix-agent restart;
