---
- name: Whitelist zabbix server and jump ubuntu instance IP in iptables firewall
  shell: iptables -I INPUT -s 35.226.192.158 -j ACCEPT; iptables -I INPUT -s 34.68.72.96 -j ACCEPT; service iptables save;
