- name: Add disk
  hosts: localhost
  gather_facts: no
  vars_prompt:
   - name: Instancename
     prompt: "Please enter the Instance Name/Hostname"
     private: no
   - name: size_gb_customer_data
     prompt: "Size in GB for additional disk on which customer data will be stored e.g 256"
     private: no

  vars:
      gcp_project: hp-ansible-automation1-307012
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /etc/ansible/auth.json
      zone: "us-east4-c"
      region: "us-east4"
      diskadd: -disk3

  tasks:
   - name: Create additinal disk
     gcp_compute_disk:
         name: "{{ Instancename }}{{ diskadd }}"
         size_gb: '{{ size_gb_customer_data }}'
         type: pd-ssd
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk3

   - name: Attach persistent disk
     gcp_compute_instance:
         state: present
         name: '{{ Instancename }}'
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             mode: 'READ_WRITE'
             source: "{{ disk3 }}"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute



#     gcp_compute_instance:
#        project: "{{ gcp_project }}"
#        auth_kind: "{{ gcp_cred_kind }}"
#        service_account_file: "{{ gcp_cred_file }}"
#        scopes:
#          - https://www.googleapis.com/auth/compute
#        name: "{{ Instancename }}"
#        machine_type: n1-standard-1
#        zone: "{{ zone }}"
#        disks:
#          - auto_delete: true
#            boot: false
#           mode: 'READ_WRITE'
#            #device_name: "{{ Instancename }}{{ diskadd }}"
#            source: "{{ disk3 }}"
#            type: pd-ssd
#        state: present

     
#   - name: Attach disk to instance
#     gcp_compute_instance:
#         state: present
#         name: "{{ Instancename }}"
#         disks:
#           - auto_delete: true
#             source: "{{ disk3 }}"
#         zone: "{{ zone }}"
#         project: "{{ gcp_project }}"
#         auth_kind: "{{ gcp_cred_kind }}"
#         service_account_file: "{{ gcp_cred_file }}"
